channels:
- defaults
dependencies:
- python=3.6.9
- pip==19.3.1
- pip:
  - scikit-learn==0.22.1
  - scipy==1.5.1
  - numpy==1.19.2
  - pandas==1.0.5
  - nltk==3.5
  - tweepy==3.9.0
  - preprocessor==1.1.3
  - plotly==4.8.1
  - Flask==1.1.2
  - flake8==3.5.0
  - matplotlib==3.3.4
name: conda-tesla